[project]
name = "fsim"
version = "0.0.1"
description = "PPSFP (Parallel-Pattern Single-Fault Propagation) style fault simulators and other utility functions for use in various projects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kyupy",
    "numba>=0.65.1",
    "numba-cuda[cu13]>=0.30.1; sys_platform != 'darwin'",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "isort>=8.0.1",
    "pytest>=9.0.1",
    "ipython>=9.14.1",
    "jupyter>=1.1.1",
    "graphviz",
]

[tool.uv.workspace]
members = [
    "kyupy",
]

[tool.uv.sources]
kyupy = { workspace = true, editable = true }

